### ISSUE TITLE
Diseño inicial 3D del chasis

### ISSUE THREAD

**Issue by GioSunrider** [GioSunrider/OmniRobot#2]
Se tiene que decidir la forma del coche, para ello es necesario la decision de 3 o 4 ruedas. Una vez elegido, se debe comenzar con el diseño en 3D. Se propone imprmirlo en PETG ya que aguanta mas los golpes.

**Comment by GioSunrider** [comment]
Se realizan las siguientes propuestas de diseño:

![photo5825418127188537376](https://user-images.githubusercontent.com/10605193/50281762-cb869380-0450-11e9-801b-87f2cf2a8dbe.jpg)

![photo5825418127188537377](https://user-images.githubusercontent.com/10605193/50281764-cd505700-0450-11e9-88cd-2f95a8d76484.jpg)

**Comment by David-Estevez** [comment]
Yo empezaría por la solución de 3 ruedas, que creo que nos daría las siguentes ventajas:

* Menos motores
* Menos consumo
* Más barato

El único (pequeño) inconveniente es que el control será ligeramente más complicado, pero el control es algo que ya está resuelto por otras personas.

**Comment by GioSunrider** [comment]
Si, yo tambien creia lo mismo. Y si nos venimos arriba hacer un segundo pero de 4 ruedas, hacer el chasis no cuesta nada y como se imprime....

**Comment by GioSunrider** [comment]
Se ha realizado la opcion uno, diseñada en FreeCad. y se ha subido al repo aa8b9a0, queda, cuando se encuentren motores, realizar los agujeros correspondientes para encajar en el propio chasis.

**Comment by GioSunrider** [comment]
Se ha realizado un primer diseño con el soporte para motores, subido en 383bda1.

**Comment by GioSunrider** [comment]
Visto que la primera version del chasis las ruedas no legaban a tocar el suelo, se ha invertido la colocacion de los motores y se ha subido al repo en 383bda1. 
Cabe decir que al exportarlo en .st y generar el .gcode, la malla no estaba bien construida, por lo que se ha pasado el 'Motor Mount V2.stl' por la herramient de Microsoft ['3D Tools'](https://tools3d.azurewebsites.net/), que repara la malla de forma automatica. 
Por lo que a la hora de generar el .gode se usara el archivo reparado '.3mf'.

**Comment by GioSunrider** [comment]
La impresion del chasis V2.0  ha sido un exito, tal y como se muestra en la imagen. Se han solventado los errores de la anterior impresion.

![photo5922360370897465180](https://user-images.githubusercontent.com/10605193/51495549-0e73b800-1dbd-11e9-8fab-d5eca10aeeba.jpg)

**Comment by GioSunrider** [comment]
como se muestra en #4 la colocacion del motor en el chasis es perfecta, habra que hacer futuros rediseños para la colocacion del resto de cosas, pero este queda como funcional.
