### ISSUE TITLE
Colocar las ruedas en el motor

### ISSUE THREAD

**Issue by GioSunrider** [GioSunrider/OmniRobot#3]
Actualmente se dispone de las siguientes ruedas:

![rueda-omnidireccional-40mm](https://user-images.githubusercontent.com/10605193/50253351-3cdf2b80-03ea-11e9-8f83-ebb7231b961b.jpg)
 
Aparentemente no hay manera de colocar el eje de las ruedas en un motor, por lo que hay que investigar como se podria realizar.

**Comment by GioSunrider** [comment]
Al parecer las ruedas se ajustan por presion con un adaptador, hasta ahora lo unico que he encontrado es la foto que lo prueba.

![img_0942_72_2](https://user-images.githubusercontent.com/10605193/50254371-128f6d00-03ee-11e9-96f9-8f48e5d0e64d.jpg)

Habra que seguir buscando para ver como conseguir el adaptador.

**Comment by GioSunrider** [comment]
Se han encontrado la siguiente forma de encajar las ruedas en el motor, al parecer es como una tuerca en la que encaja el motor y se fija con una arandela y un tornillo.

![htb13vahlvxxxxa3xvxxq6xxfxxxu](https://user-images.githubusercontent.com/10605193/50281817-0092e600-0451-11e9-818c-0c0c3d65e7be.jpg)

![htb1tduylvxxxxbcaxxxq6xxfxxxh](https://user-images.githubusercontent.com/10605193/50281819-02f54000-0451-11e9-8b03-45bc26c26a69.jpg)

![htb1nrcslvxxxxckxpxxq6xxfxxx2](https://user-images.githubusercontent.com/10605193/50281821-04266d00-0451-11e9-9061-d7eb3ba36f6a.jpg)

**Comment by GioSunrider** [comment]
Es un acoplamiento, 8mm to 4mm.

**Comment by GioSunrider** [comment]
Creo que [estos](https://es.aliexpress.com/store/product/A-motor-shaft-coupling-coupling-4-8mm-Omni-wheel-skate-wheels-car-motor-connector-Aluminum-Alloy/815142_32814353323.html?spm=a219c.search0604.3.122.6b3464acPIS37F&ws_ab_test=searchweb0_0,searchweb201602_3_10065_10068_10547_319_10891_317_10548_10696_453_10084_454_10083_10618_10307_10820_10301_10821_538_10303_537_536_10059_10884_10887_100031_321_322_10103_5727015_5727515,searchweb201603_53,ppcSwitch_0&algo_expid=89810bf1-4ac4-4255-bba1-880344c2eed8-18&algo_pvid=89810bf1-4ac4-4255-bba1-880344c2eed8) podrian valer.

**Comment by David-Estevez** [comment]
Es posible que esos funcionen, pero son casi más caros que la rueda suelta :open_mouth: 

Tendremos que buscar una alternativa más barata en Aliexpress.

**Comment by GioSunrider** [comment]
Me di cuenta del precio, pero no he encontrado otro redondo, ya que el resto son todos con cabezal hexagonal.

**Comment by GioSunrider** [comment]
Por mucho que busco no encuentro más sujeciones que sean acordes a las dimensiones y al tipo de rueda 😭

**Comment by GioSunrider** [comment]
vale he encontrado [este modelo mas barato](https://es.aliexpress.com/store/product/4mm-Aluminum-Mounting-Coupling-Universal-Hub-For-48mm-Mecanum-Omni-Wheel-Omnidirectional-Wheels-For-DIY-Robot/3619085_32862383619.html?spm=a219c.search0104.3.134.71336c33Ya3DQv&ws_ab_test=searchweb0_0,searchweb201602_4_10065_10068_10890_10547_319_10546_317_10548_10696_453_10084_454_10083_10618_431_10307_10820_10303_537_536_10059_10884_10887_100031_321_322_10103,searchweb201603_51,ppcSwitch_0&algo_expid=f1210d98-d417-433c-8796-cd7f73e7d2c7-19&algo_pvid=f1210d98-d417-433c-8796-cd7f73e7d2c7&transAbTest=ae803_4) y [este otro](https://es.aliexpress.com/store/product/1set-Metal-Plastic-Coupling-Set-For-48mm-58mm-Mecanum-Omni-Wheel-For-Robot-Kit-And-Servo/3619085_32856499736.html?spm=a219c.search0104.3.213.755a36f05nRUUv&ws_ab_test=searchweb0_0,searchweb201602_4_10065_10068_10890_10547_319_10546_317_10548_10696_453_10084_454_10083_10618_431_10307_10820_10303_537_536_10059_10884_10887_100031_321_322_10103,searchweb201603_51,ppcSwitch_0&algo_expid=4dd70a8f-cc74-419a-85d5-d84dba4e7ebe-31&algo_pvid=4dd70a8f-cc74-419a-85d5-d84dba4e7ebe&transAbTest=ae803_4) mas o menos por el mismo precio.

**Comment by GioSunrider** [comment]
Se ha realizado una prueba de concepto imprimiendo en PLA y colocando los acoplamientos en la rueda, tal y como se muestran en las fotografias.

![photo5900010250147311506](https://user-images.githubusercontent.com/10605193/51113321-f242aa80-1801-11e9-9aa4-5f14d064a2b8.jpg)

![photo5900010250147311516](https://user-images.githubusercontent.com/10605193/51113326-f4a50480-1801-11e9-99e5-90e09412456a.jpg)

La rueda queda bien sujeta y daria la prueba como satisfactoria.
Para la prueba se han diseñado los acoplamientos, y se han parametrizado para su facilidad de cambio de diametros y ajuste posterior. Las piezas se subiran al repo.
El proximo paso seria imprimirlo en PETG que ganariamos resistencia mecanica.

**Comment by GioSunrider** [comment]
Se han subido los archivos  154da56

**Comment by GioSunrider** [comment]
Se han impreso los adaptadores en PETG, cuando estén instalados en las ruedas se podrá dar por cerrada la issue.

**Comment by GioSunrider** [comment]
Para evitar la rotacion hace falta colocar unas juntas de goma para que no deslice.

**Comment by GioSunrider** [comment]
Se tiene que rediseñar la pieza de sujecion dado que el eje del motor es bastante superior. Al estar la pieza hecha parametrica no sera mucho problema.

**Comment by GioSunrider** [comment]
Se han impreso unos acomplamientos en PETG actualmente colocados junto con dos juntas cada uno para que no deslice, tambien se han impreso en TPU para probar el resultado.
