### ISSUE TITLE
Busqueda de Motores

### ISSUE THREAD

**Issue by GioSunrider** [GioSunrider/OmniRobot#4]
Es necesario buscar el modelo de motores que se instalen. Como se menciona en #2 para rematar el chasis, ademas es importante tener en cuenta #3

**Comment by GioSunrider** [comment]
Una aproximacion de moteres pueden ser [estos](https://www.pololu.com/product/2286) aunque sin encoder, ya que en principio no es necesario.

**Comment by GioSunrider** [comment]
[Este motor](https://m.banggood.com/DC-12V-300RPM-Geared-Motor-High-Torque-37GB-550-Gear-Reducer-Motor-p-1068575.html?rmmds=myorder&cur_warehouse=CN) es un gran firme candidato. Motor de 12V 300rpm y alto par.

**Comment by GioSunrider** [comment]
[Este Motor sera EL ELEGIDO](https://www.banggood.com/es/DC-6V-90RPM-Geared-Motor-37GB-550-High-Torque-Gear-Reducer-Motor-p-1068574.html?rmmds=detail-left-hotproducts__1&cur_warehouse=CN)

**Comment by David-Estevez** [comment]
Para poder avanzar habría que comprar al menos 1 motor... puedo preguntar en el departamento a ver si han abierto de nuevo la veda para los TFGs...

**Comment by GioSunrider** [comment]
Genial, pues ya me dirás la confirmación.

**Comment by GioSunrider** [comment]
[Este motor](https://www.pololu.com/product/1106/specs) es el mismo del anterior pero de un distribuidor oficial.

**Comment by GioSunrider** [comment]
Se ha obtenido el motor, via departamento y se ha instalado en el chasis.

![photo5778364170595578076](https://user-images.githubusercontent.com/10605193/54089496-ad527480-4369-11e9-89d0-7c138647173b.jpg)
