### ISSUE TITLE
Cinematica de movimiento

### ISSUE THREAD

**Issue by GioSunrider** [GioSunrider/OmniRobot#5]
Estudiar la cinematica del movimiento para una posterior programacion.
Estos dibujos ayudaran a ello.

![diagram-of-the-holonomic-omnidirectional-mobile-robot](https://user-images.githubusercontent.com/10605193/51674098-0cce0e00-1fd0-11e9-87e6-1d51176813f0.png)

![a19_03a](https://user-images.githubusercontent.com/10605193/51674108-135c8580-1fd0-11e9-8464-02dab6fab535.jpg)

![a19_04](https://user-images.githubusercontent.com/10605193/51674105-10fa2b80-1fd0-11e9-88da-dd429adfc5a5.jpg)

**Comment by David-Estevez** [comment]
No es que ayuden, es que el de en medio ya te está diciendo cuál es la cinemática inversa del robot :joy:

**Comment by GioSunrider** [comment]
Jjajajajajaja entontes perfecto, ahora a pasarla a codigo.

**Comment by David-Estevez** [comment]
https://en.wikipedia.org/wiki/Reinventing_the_wheel

**Comment by GioSunrider** [comment]
No hay tanta informacion, pero por pasarla a codigo no era mas que ver que hay primero. reeeellaaaax que no soy tan loco.

**Comment by David-Estevez** [comment]
https://github.com/bqlabs/loki/blob/develop/loki/loki/loki.ino

**Comment by GioSunrider** [comment]
Creo que ahora mismo te voy a hacer un pedestal 🤣

**Comment by GioSunrider** [comment]
Se ha actualizado el codigo usado en el robot en 86dccc9  que controla los movimientos.
